# -*- coding: utf-8 -*-
"""Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uzyj_21F1u0ijvjPyajR55Qhi2pN37jm
"""



def get_numbers():
    """ getting 5 numbers as input and put them in a list. while it is a number -not character- continue"""
    numbers = list()
    while len(numbers) != 5:
        try:
            number = input('Enter a number: ')
            number = int(number)
            numbers.append(number)
        except ValueError:
            print('A valid input is required')
    return numbers


def get_total(numbers):
    """ calculating the sum of numbers"""
    return sum(numbers)


def print_total(total):
    """ printing the result as output """
    print(f'The total is {total}.')  


if __name__ == "__main__":
    """ implementation """
    print_header()
    numbers = get_numbers()
    total = get_total(numbers)
    
    print_total(total)


